module.exports = {
  'Babel': require('./Babel'),
  'Beautify': require('./Beautify'),
  'CleanHTML': require('./CleanHTML'),
  'CompileHandlebars': require('./CompileHandlebars'),
  'Concat': require('./Concat'),
  'Data': require('./Data'),
  'Declare': require('./Declare'),
  'DelSync': require('./DelSync'),
  'Flatten': require('./Flatten'),
  'FolderIndex': require('./FolderIndex'),
  'Minify': require('./Minify'),
  'MinifyHTML': require('./MinifyHTML'),
  'PrettyPrint': require('./PrettyPrint'),
  'Rename': require('./Rename'),
  'Rollup': require('./Rollup'),
  'SASS': require('./SASS'),
  'String': require('./String'),
  'Wrap': require('./Wrap'),
}
