module.exports = {
  'Babel': require('./Babel.js'),
  'Beautify': require('./Beautify.js'),
  'CleanHTML': require('./CleanHTML.js'),
  'CompileHandlebars': require('./CompileHandlebars.js'),
  'Concat': require('./Concat.js'),
  'Data': require('./Data'),
  'Declare': require('./Declare.js'),
  'DelSync': require('./DelSync.js'),
  'Flatten': require('./Flatten.js'),
  'FolderIndex': require('./FolderIndex.js'),
  'Minify': require('./Minify.js'),
  'MinifyHTML': require('./MinifyHTML.js'),
  'PrettyPrint': require('./PrettyPrint.js'),
  'Rename': require('./Rename.js'),
  'SASS': require('./SASS.js'),
  'SourceMaps': require('./SourceMaps.js'),
  'String': require('./String'),
  'Wrap': require('./Wrap.js'),
}