Resume.Templates.Profile = function(data) {
  var template = Array(
    '<!-- Profile -->',
    '<div data-class="fieldset" data-id="profile">',
      '<div data-class="fieldset-label">Profile</div>',
      '<div data-class="field">',
        '<label>First Name</label>',
        '<input type=text data-id="first-name">',
      '</div>',
      '<div data-class="field">',
        '<label>Last Name</label>',
        '<input type=text data-id="last-name">',
      '</div>',
      '<div data-class="field">',
        '<label>Title</label>',
        '<input type=text data-id="title">',
      '</div>',
    '</div>',
    '<!-- Links -->',
    '<div data-class="fieldset" data-id="profile-links">',
      '<div data-class="fieldset-label">Links</div>',
    '</div>',
    '<!-- Summary -->',
    '<div data-class="fieldset" data-id="profile-summary">',
      '<div data-class="fieldset-label">Summary</div>',
      '<div data-class="field">',
        '<label>Summary Type</label>',
        '<span>Description</span>',
        '<input type="radio" name="summary-type" data-class="summary-type" value="description">',
        '<span>List</span>',
        '<input type="radio" name="summary-type" data-class="summary-type value="list">',
      '</div>',
      '<div data-class="field">',
        '<label>Summary Label</label>',
        '<input type="text" data-class="summary-label">',
        '<label>Summary Description</label>',
        '<textarea type="text" data-class="summary"></textarea>',
      '</div>',
      '<div data-class="field">',
      '</div>',
    '</div>'
  ).join('');
  return document.createRange().createContextualFragment(template);
};
